name: release

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build package using Poetry and store result."
        uses: jjmerchante/actions/build@main
        with:
          artifact-name: grimoire-dist
          artifact-path: dist

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Create a new release for the repository."
        uses: jjmerchante/actions/release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Publish the package in PyPI."
        uses: jjmerchante/actions/publish@main
        with:
          artifact-name: grimoire-dist
          artifact-path: dist
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
